spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/prioritize
    url: jdbc:postgresql://memoryalpha:5431/prioritize
    username: prioritize
    password: prioritize
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect

flowable:
  database-schema: public
  database-schema-update: true
  # Das hier ersetzt den manuellen Prefix-Code in der Java-Klasse:
  table-prefix: flowable.

logging:
  level:
    org:
      springframework:
        security: INFO
      hibernate:
        SQL: INFO
        orm.results: INFO
        orm.jdbc.bind: INFO
        #Falls du noch mehr Details zum Schema-Export willst:
        tool.schema: INFO
