spring:
  profiles:
      active: postgres

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  application:
    name: prioritize

server:
  tomcat:
    basedir: tomcat
    accesslog:
      directory: logs

logging:
  level:
    org.flowable: INFO
  #file:
    #name: logs/Prioritize.log